version: '3.8'

volumes:
    php-fpm-socket:

services:
    app:
        container_name: appp
        build: ./docker/app
        volumes:
            - type: bind
              source: ./src
              target: /var/www
            - type: volume
              source: php-fpm-socket
              target: /var/run/php-fpm
              volume:
                  nocopy: true
        environment:
            - TZ=Asia/Tokyo
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306

    nginx:
        image: nginx
        container_name: nginxx
        ports:
            - 80:80
        volumes:
            - type: bind
              source: ./src
              target: /var/www
            - type: bind
              source: ./docker/nginx/default.conf
              target: /etc/nginx/conf.d/default.conf
            - type: volume
              source: php-fpm-socket
              target: /var/run/php-fpm
              volume:
                  nocopy: true

    db:
        image: mysql:5.7
        container_name: dbb
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/db/data:/var/lib/mysql
#             - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
#             - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306